import test from "node:test";
import assert from "node:assert/strict";
import {
  buildMappingConfigFromEnv,
  resolveAgent,
  resolveTool,
  resolveUser,
  slugify
} from "../src/core/mapping.mjs";

const TOOL_ID = "pub_UnderwriterCopilot.action.UnderwriterCopilotTools-UnderwriterCopilotTools_nAl";

test("slugify turns a display name into a topology id", () => {
  assert.equal(slugify("Underwriter Copilot"), "underwriter-copilot");
  assert.equal(slugify("Send-Notification-Email"), "send-notification-email");
  assert.equal(slugify("", "fallback"), "fallback");
});

test("explicit id map wins over name and slug", () => {
  const cfg = buildMappingConfigFromEnv({ REVA_TOOL_ID_MAP: JSON.stringify({ [TOOL_ID]: "send-notification-email" }) });
  const r = resolveTool({ id: TOOL_ID, name: "Anything At All" }, cfg);
  assert.equal(r.id, "send-notification-email");
  assert.equal(r.via, "id-map");
  assert.equal(r.mapped, true);
});

test("name map is the second rung", () => {
  const cfg = buildMappingConfigFromEnv({ REVA_TOOL_ID_MAP: JSON.stringify({ "Send-Notification-Email": "send-notification-email" }) });
  const r = resolveTool({ id: "unknown-id", name: "Send-Notification-Email" }, cfg);
  assert.equal(r.id, "send-notification-email");
  assert.equal(r.via, "name-map");
});

test("lookup is case-insensitive", () => {
  const cfg = buildMappingConfigFromEnv({ REVA_AGENT_ID_MAP: JSON.stringify({ "underwriter copilot": "uc" }) });
  assert.equal(resolveAgent({ name: "Underwriter Copilot" }, cfg).id, "uc");
});

test("slug fallback keeps working with no configuration, but is marked unmapped", () => {
  const cfg = buildMappingConfigFromEnv({});
  const r = resolveTool({ id: TOOL_ID, name: "Send-Notification-Email" }, cfg);
  // Backward compatible with the deployed v1 behaviour...
  assert.equal(r.id, "send-notification-email");
  // ...but flagged, because a Copilot Studio rename would silently change the resolved id.
  assert.equal(r.via, "slug");
  assert.equal(r.mapped, false);
});

test("the opaque Power Platform id suffix is never used as an entity id", () => {
  const cfg = buildMappingConfigFromEnv({});
  // "_nAl" is generated by Power Platform and is not stable across solution re-imports.
  assert.ok(!resolveTool({ id: TOOL_ID, name: "Send-Notification-Email" }, cfg).id.includes("nal"));
});

test("users pass their Entra GUID through when unmapped", () => {
  const cfg = buildMappingConfigFromEnv({});
  const r = resolveUser("22222222-2222-2222-2222-222222222222", cfg);
  // The store may legitimately key users by IdP subject, so identity is the right fallback.
  assert.equal(r.id, "22222222-2222-2222-2222-222222222222");
  assert.equal(r.via, "passthrough");
});

test("users resolve through the principal map when present", () => {
  const cfg = buildMappingConfigFromEnv({ REVA_PRINCIPAL_ID_MAP: JSON.stringify({ "22222222-2222-2222-2222-222222222222": "alice" }) });
  assert.equal(resolveUser("22222222-2222-2222-2222-222222222222", cfg).id, "alice");
});

test("an unmapped entity still resolves to a usable id — mapping is not required", () => {
  // pr06 evaluates ids that exist nowhere in the store (2026-09-10), so the slug fallback is
  // an ordinary outcome rather than a misconfiguration to refuse. REVA_ON_UNMAPPED_ENTITY
  // used to turn this into a pre-flight denial; it was blocking calls the PDP allows.
  const cfg = buildMappingConfigFromEnv({});
  const agent = resolveAgent({ id: "33333333-3333-3333-3333-333333333333", name: "Underwriter Copilot" }, cfg);
  assert.equal(agent.id, "underwriter-copilot");
  assert.equal(agent.mapped, false);
  // Still reported, so an unmapped id remains visible on every event.
  assert.equal(agent.via, "slug");
});

test("REVA_ON_UNMAPPED_ENTITY is gone and setting it changes nothing", () => {
  const withFlag = buildMappingConfigFromEnv({ REVA_ON_UNMAPPED_ENTITY: "deny" });
  assert.deepEqual(withFlag, buildMappingConfigFromEnv({}));
  assert.equal(withFlag.onUnmapped, undefined);
});

test("malformed map JSON degrades to empty rather than throwing", () => {
  const cfg = buildMappingConfigFromEnv({ REVA_TOOL_ID_MAP: "{not json" });
  assert.deepEqual(cfg.tools, {});
});
